//! Enums for the broker API, from `alpaca/broker/enums.py`.
//!
//! Generated by `scripts/gen_enums.py` from `alpaca/broker/enums.py`
//! at alpaca-py revision `cc4cb3b`. Do not edit by hand — hand-written
//! `impl` blocks belong in the sibling `enums_ext.rs`.

use crate::types::wire::wire_enum;
wire_enum! {
    /// The sub type of account
    /// IRA Account only
    ///
    /// see <https://docs.alpaca.markets/reference/createaccount>
    pub enum AccountSubType {
        /// `traditional`
        Traditional => "traditional",
        /// `roth`
        Roth => "roth",
    }
}

wire_enum! {
    /// The type of account
    ///
    /// see <https://docs.alpaca.markets/reference/createaccount>
    pub enum AccountType {
        /// `trading`
        Trading => "trading",
        /// `custodial`
        Custodial => "custodial",
        /// `donor_advised`
        DonorAdvised => "donor_advised",
        /// `ira`
        Ira => "ira",
        /// `hsa`
        Hsa => "hsa",
    }
}

wire_enum! {
    /// The various country specific tax identification numbers
    ///
    /// see <https://alpaca.markets/docs/broker/api-references/accounts/accounts/#tax-id-type>
    pub enum TaxIdType {
        /// `USA_SSN`
        UsaSsn => "USA_SSN",
        /// `USA_ITIN`
        UsaItin => "USA_ITIN",
        /// `ARG_AR_CUIT`
        ArgArCuit => "ARG_AR_CUIT",
        /// `AUS_TFN`
        AusTfn => "AUS_TFN",
        /// `AUS_ABN`
        AusAbn => "AUS_ABN",
        /// `BOL_NIT`
        BolNit => "BOL_NIT",
        /// `BRA_CPF`
        BraCpf => "BRA_CPF",
        /// `CHL_RUT`
        ChlRut => "CHL_RUT",
        /// `COL_NIT`
        ColNit => "COL_NIT",
        /// `CRI_NITE`
        CriNite => "CRI_NITE",
        /// `DEU_TAX_ID`
        DeuTaxId => "DEU_TAX_ID",
        /// `DOM_RNC`
        DomRnc => "DOM_RNC",
        /// `ECU_RUC`
        EcuRuc => "ECU_RUC",
        /// `FRA_SPI`
        FraSpi => "FRA_SPI",
        /// `GBR_UTR`
        GbrUtr => "GBR_UTR",
        /// `GBR_NINO`
        GbrNino => "GBR_NINO",
        /// `GTM_NIT`
        GtmNit => "GTM_NIT",
        /// `HND_RTN`
        HndRtn => "HND_RTN",
        /// `HUN_TIN`
        HunTin => "HUN_TIN",
        /// `IDN_KTP`
        IdnKtp => "IDN_KTP",
        /// `IND_PAN`
        IndPan => "IND_PAN",
        /// `ISR_TAX_ID`
        IsrTaxId => "ISR_TAX_ID",
        /// `ITA_TAX_ID`
        ItaTaxId => "ITA_TAX_ID",
        /// `JPN_TAX_ID`
        JpnTaxId => "JPN_TAX_ID",
        /// `MEX_RFC`
        MexRfc => "MEX_RFC",
        /// `NIC_RUC`
        NicRuc => "NIC_RUC",
        /// `NLD_TIN`
        NldTin => "NLD_TIN",
        /// `PAN_RUC`
        PanRuc => "PAN_RUC",
        /// `PER_RUC`
        PerRuc => "PER_RUC",
        /// `PRY_RUC`
        PryRuc => "PRY_RUC",
        /// `SGP_NRIC`
        SgpNric => "SGP_NRIC",
        /// `SGP_FIN`
        SgpFin => "SGP_FIN",
        /// `SGP_ASGD`
        SgpAsgd => "SGP_ASGD",
        /// `SGP_ITR`
        SgpItr => "SGP_ITR",
        /// `SLV_NIT`
        SlvNit => "SLV_NIT",
        /// `SWE_TAX_ID`
        SweTaxId => "SWE_TAX_ID",
        /// `URY_RUT`
        UryRut => "URY_RUT",
        /// `VEN_RIF`
        VenRif => "VEN_RIF",
        /// `NATIONAL_ID`
        NationalId => "NATIONAL_ID",
        /// `PASSPORT`
        Passport => "PASSPORT",
        /// `PERMANENT_RESIDENT`
        PermanentResident => "PERMANENT_RESIDENT",
        /// `DRIVER_LICENSE`
        DriverLicense => "DRIVER_LICENSE",
        /// `OTHER_GOV_ID`
        OtherGovId => "OTHER_GOV_ID",
        /// `NOT_SPECIFIED`
        NotSpecified => "NOT_SPECIFIED",
    }
}

wire_enum! {
    /// In addition to the following USA visa categories, we accept any sub visas of the list below.
    /// Sub visas must be passed in according to their parent category.
    /// Note that United States green card holders are considered permanent residents and should not pass in a visa type.
    ///
    /// Please feel free to reach out to Alpaca if you need other tax ID types.
    ///
    /// see <https://alpaca.markets/docs/broker/api-references/accounts/accounts/#visa-type>
    pub enum VisaType {
        /// `B1`
        B1 => "B1",
        /// `B2`
        B2 => "B2",
        /// `DACA`
        Daca => "DACA",
        /// `E1`
        E1 => "E1",
        /// `E2`
        E2 => "E2",
        /// `E3`
        E3 => "E3",
        /// `F1`
        F1 => "F1",
        /// `G4`
        G4 => "G4",
        /// `H1B`
        H1b => "H1B",
        /// `J1`
        J1 => "J1",
        /// `L1`
        L1 => "L1",
        /// `OTHER`
        Other => "OTHER",
        /// `O1`
        O1 => "O1",
        /// `TN1`
        Tn1 => "TN1",
    }
}

wire_enum! {
    /// Various sources of funding for brokerage accounts.
    ///
    /// see <https://alpaca.markets/docs/broker/api-references/accounts/accounts/#funding-source>
    pub enum FundingSource {
        /// `employment_income`
        EmploymentIncome => "employment_income",
        /// `investments`
        Investments => "investments",
        /// `inheritance`
        Inheritance => "inheritance",
        /// `business_income`
        BusinessIncome => "business_income",
        /// `savings`
        Savings => "savings",
        /// `family`
        Family => "family",
    }
}

wire_enum! {
    /// The possible employment statuses of the user
    ///
    /// see <https://alpaca.markets/docs/broker/api-references/accounts/accounts/#employment-status>
    pub enum EmploymentStatus {
        /// `UNEMPLOYED`
        Unemployed => "UNEMPLOYED",
        /// `EMPLOYED`
        Employed => "EMPLOYED",
        /// `STUDENT`
        Student => "STUDENT",
        /// `RETIRED`
        Retired => "RETIRED",
    }
}

wire_enum! {
    /// The types of agreements that are to be signed by the user
    ///
    /// see <https://docs.alpaca.markets/reference/createaccount>
    pub enum AgreementType {
        /// `margin_agreement`
        Margin => "margin_agreement",
        /// `account_agreement`
        Account => "account_agreement",
        /// `customer_agreement`
        Customer => "customer_agreement",
        /// `crypto_agreement`
        Crypto => "crypto_agreement",
        /// `options_agreement`
        Options => "options_agreement",
        /// `custodial_customer_agreement`
        CustodialCustomer => "custodial_customer_agreement",
    }
}

wire_enum! {
    /// Represents the kind of document data you're uploading
    ///
    /// please see <https://alpaca.markets/docs/broker/api-references/accounts/accounts/#document-type>
    /// and <https://alpaca.markets/docs/api-references/broker-api/documents/#enumuploaddocumenttype>
    /// for more info
    pub enum DocumentType {
        /// `identity_verification`
        IdentityVerification => "identity_verification",
        /// `address_verification`
        AddressVerification => "address_verification",
        /// `date_of_birth_verification`
        DateOfBirthVerification => "date_of_birth_verification",
        /// `tax_id_verification`
        TaxIdVerification => "tax_id_verification",
        /// `account_approval_letter`
        AccountApprovalLetter => "account_approval_letter",
        /// `limited_trading_authorization`
        LimitedTradingAuthorization => "limited_trading_authorization",
        /// `w8ben`
        W8ben => "w8ben",
        /// `social_security_number_verification`
        SocialSecurityNumberVerification => "social_security_number_verification",
        /// The empty value.
        Null => "",
        /// `cip_result`
        CipResult => "cip_result",
        /// `other`
        Other => "other",
    }
}

wire_enum! {
    /// An enum representing the different fields to query for when listing accounts.
    ///
    /// ie: asking for CONTACT and IDENTITY will have the api fill those fields when returning the list of Accounts however
    /// other fields on the account will be nulled out where possible.
    pub enum AccountEntities {
        /// `contact`
        Contact => "contact",
        /// `identity`
        Identity => "identity",
        /// `disclosures`
        Disclosures => "disclosures",
        /// `agreements`
        Agreements => "agreements",
        /// `documents`
        Documents => "documents",
        /// `trusted_contact`
        TrustedContact => "trusted_contact",
        /// `trading_configurations`
        UserConfigurations => "trading_configurations",
    }
}

wire_enum! {
    /// An enum for representing what Clearing broker an Account is assigned to
    pub enum ClearingBroker {
        /// `APEX`
        Apex => "APEX",
        /// `ETC`
        Etc => "ETC",
        /// `IC`
        Ic => "IC",
        /// `VELOX`
        Velox => "VELOX",
        /// `VISION`
        Vision => "VISION",
        /// `SELF`
        SelfClearing => "SELF",
        /// `ALPACA_APCA`
        AlpacaApca => "ALPACA_APCA",
    }
}

wire_enum! {
    /// Enum representing what CIP provider was used.
    ///
    /// see <https://alpaca.markets/docs/api-references/broker-api/accounts/accounts/#cip-provider> for more info
    pub enum CIPProvider {
        /// `alloy`
        Alloy => "alloy",
        /// `trulioo`
        Trulioo => "trulioo",
        /// `onfido`
        Onfido => "onfido",
        /// `veriff`
        Veriff => "veriff",
        /// `jumio`
        Jumio => "jumio",
        /// `getmati`
        Getmati => "getmati",
    }
}

wire_enum! {
    /// An enum representing the status of the `CIPInfo`
    ///
    /// see <https://alpaca.markets/docs/api-references/broker-api/accounts/accounts/#cip-status> for more info
    pub enum CIPStatus {
        /// `complete`
        Complete => "complete",
        /// `withdrawn`
        Withdrawn => "withdrawn",
    }
}

wire_enum! {
    /// see <https://alpaca.markets/docs/api-references/broker-api/accounts/accounts/#cip-result> for more info
    pub enum CIPResult {
        /// `clear`
        Clear => "clear",
        /// `consider`
        Consider => "consider",
    }
}

wire_enum! {
    /// Either `approved` or `rejected`
    pub enum CIPApprovalStatus {
        /// `approved`
        Approved => "approved",
        /// `rejected`
        Rejected => "rejected",
    }
}

wire_enum! {
    /// Represents what kind information is inside a `TradeDocument`
    ///
    /// Most likely will be either of these 3:
    /// -  `ACCOUNT_STATEMENT`
    /// -  `TRADE_CONFIRMATION`
    /// -  `TAX_STATEMENT`
    ///
    /// However, for older accounts with legacy documents the other legacy values might show up.
    ///
    /// please see <https://alpaca.markets/docs/api-references/broker-api/documents/#enumdocumenttype> for more info
    pub enum TradeDocumentType {
        /// `account_statement`
        AccountStatement => "account_statement",
        /// `trade_confirmation`
        TradeConfirmation => "trade_confirmation",
        /// `trade_confirmation_json`
        TradeConfirmationJson => "trade_confirmation_json",
        /// `tax_statement`
        TaxStatement => "tax_statement",
        /// `account_application`
        AccountApplication => "account_application",
        /// `tax_1099_b_details`
        Tax1099BDetails => "tax_1099_b_details",
        /// `tax_1099_b_form`
        Tax1099BForm => "tax_1099_b_form",
        /// `tax_1099_div_details`
        Tax1099DivDetails => "tax_1099_div_details",
        /// `tax_1099_div_form`
        Tax1099DivForm => "tax_1099_div_form",
        /// `tax_1099_int_details`
        Tax1099IntDetails => "tax_1099_int_details",
        /// `tax_1099_int_form`
        Tax1099IntForm => "tax_1099_int_form",
        /// `tax_w8`
        TaxW8 => "tax_w8",
    }
}

wire_enum! {
    /// Represents additional information for whats inside a `TradeDocument` in combination with a `TradeDocumentType`
    ///
    /// please see <https://alpaca.markets/docs/api-references/broker-api/documents/#the-document-object> for more info
    pub enum TradeDocumentSubType {
        /// `1099-Comp`
        Type1099Comp => "1099-Comp",
        /// `1042-S`
        Type1042S => "1042-S",
        /// `480.6`
        Type4806 => "480.6",
        /// `courtesy_statement`
        CourtesyStatement => "courtesy_statement",
    }
}

wire_enum! {
    /// Represents a sub type for an `UploadDocumentRequest`
    ///
    /// please see: <https://alpaca.markets/docs/api-references/broker-api/documents/#enumuploaddocumentsubtype>
    /// for more info
    pub enum UploadDocumentSubType {
        /// `Account Application`
        AccountApplication => "Account Application",
        /// `Form W-8BEN`
        FormW8Ben => "Form W-8BEN",
        /// `passport`
        Passport => "passport",
    }
}

wire_enum! {
    /// specifies the mime type of the base64 data you're uploading as part of a `UploadDocumentRequest`
    ///
    /// please see <https://alpaca.markets/docs/api-references/broker-api/documents/#parameters> for more info
    pub enum UploadDocumentMimeType {
        /// `application/pdf`
        Pdf => "application/pdf",
        /// `image/png`
        Png => "image/png",
        /// `image/jpeg`
        Jpeg => "image/jpeg",
        /// `application/json`
        Json => "application/json",
    }
}

wire_enum! {
    /// Represents the state that an `ACHRelationship` is in.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/ach/#attributes> for more details
    pub enum ACHRelationshipStatus {
        /// `QUEUED`
        Queued => "QUEUED",
        /// `APPROVED`
        Approved => "APPROVED",
        /// `PENDING`
        Pending => "PENDING",
    }
}

wire_enum! {
    /// Represents a kind of bank account.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/ach/#attributes>
    pub enum BankAccountType {
        /// `CHECKING`
        Checking => "CHECKING",
        /// `SAVINGS`
        Savings => "SAVINGS",
        /// The empty value.
        None => "",
    }
}

wire_enum! {
    /// Represents a type of bank account.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/bank/#creating-a-new-bank-relationship> for
    /// more details.
    pub enum IdentifierType {
        /// `ABA`
        Aba => "ABA",
        /// `BIC`
        Bic => "BIC",
    }
}

wire_enum! {
    /// Represents the states a Bank instance can be in.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/bank/#enumbankstatus> for more details.
    pub enum BankStatus {
        /// `QUEUED`
        Queued => "QUEUED",
        /// `SENT_TO_CLEARING`
        SentToClearing => "SENT_TO_CLEARING",
        /// `APPROVED`
        Approved => "APPROVED",
        /// `CANCELED`
        Canceled => "CANCELED",
    }
}

wire_enum! {
    /// Represents the types of transfers that can be made.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/transfers/#enumtransfertype> for more
    /// details.
    pub enum TransferType {
        /// `ach`
        Ach => "ach",
        /// `wire`
        Wire => "wire",
    }
}

wire_enum! {
    /// Represents the states a Transfer instance can be in.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/transfers/#enumtransferstatus> for more
    /// details.
    pub enum TransferStatus {
        /// `QUEUED`
        Queued => "QUEUED",
        /// `APPROVAL_PENDING`
        ApprovalPending => "APPROVAL_PENDING",
        /// `PENDING`
        Pending => "PENDING",
        /// `SENT_TO_CLEARING`
        SentToClearing => "SENT_TO_CLEARING",
        /// `REJECTED`
        Rejected => "REJECTED",
        /// `CANCELED`
        Canceled => "CANCELED",
        /// `APPROVED`
        Approved => "APPROVED",
        /// `SETTLED`
        Settled => "SETTLED",
        /// `COMPLETE`
        Complete => "COMPLETE",
        /// `RETURNED`
        Returned => "RETURNED",
    }
}

wire_enum! {
    /// Represents the direction of the transfer.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/transfers/#enumtransferdirection> for more
    /// details.
    pub enum TransferDirection {
        /// `INCOMING`
        Incoming => "INCOMING",
        /// `OUTGOING`
        Outgoing => "OUTGOING",
    }
}

wire_enum! {
    /// Represents the timing of a transfer.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/transfers/#creating-a-transfer-entity> for
    /// more details.
    pub enum TransferTiming {
        /// `immediate`
        Immediate => "immediate",
    }
}

wire_enum! {
    /// Represents who is responsible for paying fees associated with the transfer.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/funding/transfers/#enumfeepaymentmethod> for more
    /// details.
    pub enum FeePaymentMethod {
        /// `user`
        User => "user",
        /// `invoice`
        Invoice => "invoice",
    }
}

wire_enum! {
    /// Represents the types of journals. Cash journals are transfers of cash.
    /// Security journals are transfers of securities like stocks.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/journals/> for more details.
    pub enum JournalEntryType {
        /// `JNLC`
        Cash => "JNLC",
        /// `JNLS`
        Security => "JNLS",
    }
}

wire_enum! {
    /// The various states a journal can be in during its lifecycle.
    ///
    /// Please see <https://alpaca.markets/docs/api-references/broker-api/journals/#enumjournalstatus> for more details.
    pub enum JournalStatus {
        /// `queued`
        Queued => "queued",
        /// `sent_to_clearing`
        SentToClearing => "sent_to_clearing",
        /// `pending`
        Pending => "pending",
        /// `executed`
        Executed => "executed",
        /// `rejected`
        Rejected => "rejected",
        /// `canceled`
        Canceled => "canceled",
        /// `refused`
        Refused => "refused",
        /// `correct`
        Correct => "correct",
        /// `deleted`
        Deleted => "deleted",
    }
}

wire_enum! {
    /// The possible values of the Portfolio status.
    ///
    /// See <https://docs.alpaca.markets/reference/get-v1-rebalancing-portfolios>
    pub enum PortfolioStatus {
        /// `active`
        Active => "active",
        /// `inactive`
        Inactive => "inactive",
        /// `needs_adjustment`
        NeedsAdjustment => "needs_adjustment",
    }
}

wire_enum! {
    /// The possible values of the Weight type.
    ///
    /// See <https://docs.alpaca.markets/reference/post-v1-rebalancing-portfolios>
    pub enum WeightType {
        /// `cash`
        Cash => "cash",
        /// `asset`
        Asset => "asset",
    }
}

wire_enum! {
    /// The possible values of the Rebalancing Conditions type.
    ///
    /// See <https://docs.alpaca.markets/reference/post-v1-rebalancing-portfolios>
    pub enum RebalancingConditionsType {
        /// `drift_band`
        DriftBand => "drift_band",
        /// `calendar`
        Calendar => "calendar",
    }
}

wire_enum! {
    /// The possible values of the Rebalancing Conditions subtype for `drift_band`.
    ///
    /// See <https://docs.alpaca.markets/reference/post-v1-rebalancing-portfolios>
    pub enum DriftBandSubType {
        /// `absolute`
        Absolute => "absolute",
        /// `relative`
        Relative => "relative",
    }
}

wire_enum! {
    /// The possible values of the Rebalancing Conditions subtype for `drift_band`.
    ///
    /// See <https://docs.alpaca.markets/reference/post-v1-rebalancing-portfolios>
    pub enum CalendarSubType {
        /// `weekly`
        Weekly => "weekly",
        /// `monthly`
        Monthly => "monthly",
        /// `quarterly`
        Quarterly => "quarterly",
        /// `annually`
        Annually => "annually",
    }
}

wire_enum! {
    /// The possible values of the Run type.
    ///
    /// See <https://docs.alpaca.markets/reference/post-v1-rebalancing-runs>
    pub enum RunType {
        /// `full_rebalance`
        FullRebalance => "full_rebalance",
        /// `invest_cash`
        InvestCash => "invest_cash",
    }
}

wire_enum! {
    /// The possible values of the `initiated_from` field.
    ///
    /// See <https://docs.alpaca.markets/docs/portfolio-rebalancing>
    pub enum RunInitiatedFrom {
        /// `system`
        System => "system",
        /// `api`
        Api => "api",
    }
}

wire_enum! {
    /// The possible values of the Run status.
    ///
    /// See <https://docs.alpaca.markets/reference/get-v1-rebalancing-runs>
    pub enum RunStatus {
        /// `QUEUED`
        Queued => "QUEUED",
        /// `IN_PROGRESS`
        InProgress => "IN_PROGRESS",
        /// `CANCELED`
        Canceled => "CANCELED",
        /// `CANCELED_MID_RUN`
        CanceledMidRun => "CANCELED_MID_RUN",
        /// `ERROR`
        Error => "ERROR",
        /// `TIMEOUT`
        Timeout => "TIMEOUT",
        /// `COMPLETED_SUCCESS`
        CompletedSuccess => "COMPLETED_SUCCESS",
        /// `COMPLETED_ADJUSTED`
        CompletedAdjusted => "COMPLETED_ADJUSTED",
    }
}
