//! Enums shared by more than one API surface.
//!
//! Generated by `scripts/gen_enums.py` from `alpaca/trading/enums.py`
//! at alpaca-py revision `cc4cb3b`. Do not edit by hand — hand-written
//! `impl` blocks belong in the sibling `enums_ext.rs`.

use crate::types::wire::wire_enum;
wire_enum! {
    /// Represents the contract type of options
    pub enum ContractType {
        /// `call`
        Call => "call",
        /// `put`
        Put => "put",
    }
}
